# Generated by Django 5.2.17 on 2026-09-18 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_ingestao_robusta'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(verbose_name='fonte')),
                ('mode', models.TextField(choices=[('file', 'Arquivo'), ('pull', 'Consulta a fonte (polling)'), ('push', 'Entrega pela fonte (webhook)'), ('replay', 'Reprocessamento da quarentena')], default='file', verbose_name='modo')),
                ('status', models.TextField(choices=[('running', 'Em execução'), ('ok', 'Concluída'), ('partial', 'Concluída com recusas'), ('failed', 'Falhou')], default='running', verbose_name='situação')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='início')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='fim')),
                ('cursor_before', models.TextField(blank=True, null=True, verbose_name="marca d'água de partida")),
                ('cursor_after', models.TextField(blank=True, null=True, verbose_name="marca d'água de chegada")),
                ('received', models.PositiveIntegerField(default=0, verbose_name='registros recebidos')),
                ('created', models.PositiveIntegerField(default=0, verbose_name='sessões criadas')),
                ('updated', models.PositiveIntegerField(default=0, verbose_name='sessões atualizadas')),
                ('duplicates', models.PositiveIntegerField(default=0, verbose_name='duplicatas')),
                ('rejected', models.PositiveIntegerField(default=0, verbose_name='recusados')),
                ('unknown_point', models.PositiveIntegerField(default=0, verbose_name='carregador desconhecido')),
                ('conflicts', models.PositiveIntegerField(default=0, verbose_name='conflitos')),
                ('orphans', models.PositiveIntegerField(default=0, verbose_name='sessões órfãs')),
                ('readings', models.PositiveIntegerField(default=0, verbose_name='leituras de telemetria')),
                ('error', models.TextField(blank=True, null=True, verbose_name='erro')),
                ('condominium', models.ForeignKey(blank=True, help_text='Nulo quando a entrega e por push: o condominio se descobre pelo numero de serie do carregador, registro a registro.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='core.condominium')),
            ],
            options={
                'verbose_name': 'execução de ingestão',
                'verbose_name_plural': 'execuções de ingestão',
                'db_table': 'ingestion_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(verbose_name='fonte')),
                ('source_ref', models.TextField(blank=True, null=True, verbose_name='identificador na fonte')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
                ('payload', models.JSONField(verbose_name='registro bruto')),
                ('outcome', models.TextField(choices=[('created', 'Sessão criada'), ('updated', 'Sessão atualizada'), ('duplicate', 'Duplicata (ignorada)'), ('telemetry', 'Telemetria fora de sessão'), ('rejected', 'Recusado'), ('unknown_point', 'Carregador desconhecido'), ('conflict', 'Conflito com sessão já faturada')], verbose_name='desfecho')),
                ('reason', models.TextField(blank=True, help_text='Por que foi recusado, ou o que mudou na atualizacao.', null=True, verbose_name='motivo')),
                ('warnings', models.JSONField(blank=True, default=list, help_text='O registro entrou, mas algo merece olho humano: credencial revogada, sobreposicao com outra sessao no mesmo conector.', verbose_name='avisos')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Preenchido quando um reprocessamento posterior aceitou o registro.', null=True, verbose_name='resolvido em')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ingestion.ingestionrun')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_events', to='core.chargingsession')),
            ],
            options={
                'verbose_name': 'registro bruto',
                'verbose_name_plural': 'registros brutos',
                'db_table': 'ingestion_raw_event',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='ingestionrun',
            index=models.Index(fields=['source', '-started_at'], name='ingestion_r_source_ff361e_idx'),
        ),
        migrations.AddIndex(
            model_name='rawevent',
            index=models.Index(fields=['source', 'source_ref'], name='ingestion_r_source_7b89a3_idx'),
        ),
        migrations.AddIndex(
            model_name='rawevent',
            index=models.Index(condition=models.Q(('outcome__in', ['rejected', 'unknown_point', 'conflict'])), fields=['outcome'], name='raw_event_quarantine_idx'),
        ),
    ]
