# Generated by Django 5.2.17 on 2026-08-22 12:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='nome')),
                ('utility_name', models.TextField(verbose_name='distribuidora')),
                ('declared_power_kw', models.DecimalField(decimal_places=2, help_text='Teto da instalacao de recarga (Lei 18.403 / IT-41); limite do alerta de potencia da abordagem 1 de IA.', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='potencia declarada (kW)')),
                ('visitor_price_kwh', models.DecimalField(blank=True, decimal_places=4, help_text='Nula desabilita recarga de visitante.', max_digits=8, null=True, verbose_name='tarifa de visitante (R$/kWh)')),
            ],
            options={
                'verbose_name': 'condominio',
                'verbose_name_plural': 'condominios',
                'db_table': 'condominium',
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('role', models.TextField(choices=[('resident', 'Morador'), ('manager', 'Gestor/sindico'), ('visitor', 'Visitante')], default='resident', verbose_name='papel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('auth_user', models.OneToOneField(blank=True, help_text='Login do portal, quando existir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'app_user',
            },
        ),
        migrations.CreateModel(
            name='ChargePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.TextField(help_text='E o `charge_point_id` do contrato da Frente 2 (o `sn` do SEMS).', unique=True, verbose_name='numero de serie')),
                ('model', models.TextField(verbose_name='modelo')),
                ('location', models.TextField(verbose_name='localizacao')),
                ('rated_power_kw', models.DecimalField(decimal_places=2, help_text='Denominador da razao kWh/hora usada na deteccao de anomalias.', max_digits=6, verbose_name='potencia nominal (kW)')),
                ('commissioned_at', models.DateField(verbose_name='em operacao desde')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_points', to='core.condominium')),
            ],
            options={
                'verbose_name': 'ponto de recarga',
                'verbose_name_plural': 'pontos de recarga',
                'db_table': 'charge_point',
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField(choices=[('rfid', 'Cartao RFID'), ('app', 'Conta no app')], verbose_name='tipo')),
                ('auth_tag', models.TextField(help_text='UID do cartao ou id da conta -- e o `auth_id` que o carregador reporta.', unique=True, verbose_name='identificador')),
                ('status', models.TextField(choices=[('active', 'Ativa'), ('suspended', 'Suspensa'), ('revoked', 'Revogada')], default='active', verbose_name='situacao')),
                ('valid_from', models.DateField(verbose_name='valida desde')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='core.appuser')),
            ],
            options={
                'verbose_name': 'credencial',
                'db_table': 'credential',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(max_length=7, verbose_name='competencia')),
                ('status', models.TextField(choices=[('draft', 'Rascunho'), ('under_review', 'Em auditoria'), ('closed', 'Fechada'), ('paid', 'Paga'), ('overdue', 'Em atraso')], default='draft', verbose_name='situacao')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Soma das linhas, persistida no fechamento para auditoria.', max_digits=10, verbose_name='total (R$)')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='emitida em')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='vencimento')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.condominium')),
                ('visitor_user', models.ForeignKey(blank=True, help_text='Fatura avulsa de visitante, fora do rateio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitor_invoices', to='core.appuser')),
            ],
            options={
                'verbose_name': 'fatura',
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='TariffPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_kwh', models.DecimalField(decimal_places=4, help_text='Provisoria de repasse (decisao 5). O efetivo entra depois, por linha de ajuste.', max_digits=8, verbose_name='tarifa provisoria (R$/kWh)')),
                ('availability_fee_month', models.DecimalField(decimal_places=2, help_text='E o `C_disp` da formula -- valor TOTAL, rateado entre as unidades aderentes.', max_digits=10, verbose_name='taxa de disponibilidade mensal (R$)')),
                ('basis', models.TextField(help_text='Ex.: "homologada ANEEL Enel SP B3 -- bootstrap" ou "efetiva da fatura abr/2026".', verbose_name='origem do valor')),
                ('assembly_ref', models.TextField(blank=True, null=True, verbose_name='ata de assembleia')),
                ('valid_from', models.DateField(verbose_name='vigente desde')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='vigente ate')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_periods', to='core.condominium')),
            ],
            options={
                'verbose_name': 'vigencia de tarifa',
                'verbose_name_plural': 'vigencias de tarifa',
                'db_table': 'tariff_period',
            },
        ),
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_id', models.TextField(help_text='O que o carregador reportou, sem tratamento. Redundancia deliberada (decisao 2): se o cadastro for corrigido depois, a trilha de auditoria preserva o que o equipamento de fato disse.', verbose_name='identificador bruto')),
                ('auth_method', models.TextField(choices=[('rfid', 'RFID'), ('app', 'App')], verbose_name='metodo')),
                ('session_start', models.DateTimeField(verbose_name='inicio')),
                ('session_end', models.DateTimeField(blank=True, null=True, verbose_name='fim')),
                ('meter_start', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='medidor no inicio (kWh)')),
                ('meter_stop', models.DecimalField(blank=True, decimal_places=3, help_text='Nulo = leitura final perdida (caso degenerado da Opcao A): vale a ultima leitura periodica e a sessao vai para auditoria.', max_digits=12, null=True, verbose_name='medidor no fim (kWh)')),
                ('energy_kwh', models.DecimalField(decimal_places=3, help_text='E o `kwh_s` da formula de rateio.', max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='energia (kWh)')),
                ('max_power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='potencia maxima (kW)')),
                ('status', models.TextField(choices=[('in_progress', 'Em andamento'), ('completed', 'Concluida'), ('interrupted', 'Interrompida'), ('fault', 'Falha')], verbose_name='situacao')),
                ('stop_reason', models.TextField(blank=True, help_text='Vocabulario OCPP: Local, EVDisconnected, PowerLoss, EmergencyStop...', null=True, verbose_name='motivo do encerramento')),
                ('measurement_source', models.TextField(choices=[('cloud', 'Nuvem do fabricante'), ('modbus_local', 'Modbus TCP local'), ('mid_meter', 'Medidor MID (RS-485)')], default='cloud', verbose_name='origem da medicao')),
                ('applied_tariff_kwh', models.DecimalField(blank=True, decimal_places=4, help_text='Snapshot do valor provisorio no encerramento -- e a `tarifa_s` da formula (decisoes 4 e 5). Imune ate a correcao retroativa da propria vigencia.', max_digits=8, null=True, verbose_name='tarifa aplicada (R$/kWh)')),
                ('charge_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.chargepoint')),
                ('credential', models.ForeignKey(blank=True, help_text='Credencial resolvida no cadastro. Nula = sessao orfa (auth_id desconhecido) -- fica fora do rateio ate ser resolvida.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.credential')),
                ('applied_tariff', models.ForeignKey(blank=True, help_text='Vigencia aplicada; nula enquanto em andamento.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.tariffperiod')),
            ],
            options={
                'verbose_name': 'sessao de recarga',
                'verbose_name_plural': 'sessoes de recarga',
                'db_table': 'charging_session',
            },
        ),
        migrations.CreateModel(
            name='TariffReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(max_length=7, verbose_name='competencia apurada')),
                ('utility_invoice_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total da fatura da distribuidora (R$)')),
                ('utility_invoice_kwh', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='kWh faturados')),
                ('effective_price_kwh', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='tarifa efetiva (R$/kWh)')),
                ('provisional_price_kwh', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='tarifa provisoria vigente (R$/kWh)')),
                ('delta_price_kwh', models.DecimalField(decimal_places=4, help_text='Efetiva menos provisoria. Pode ser negativa.', max_digits=8, verbose_name='delta (R$/kWh)')),
                ('settled_in_competence', models.CharField(help_text='Competencia cuja fatura carrega as linhas de ajuste.', max_length=7, verbose_name='liquidada na competencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrada em')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='core.condominium')),
            ],
            options={
                'verbose_name': 'reconciliacao de tarifa',
                'verbose_name_plural': 'reconciliacoes de tarifa',
                'db_table': 'tariff_reconciliation',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField(choices=[('session', 'Sessao de recarga'), ('availability_fee', 'Taxa de disponibilidade'), ('tariff_adjustment', 'Ajuste de tarifa')], verbose_name='tipo')),
                ('description', models.TextField(verbose_name='descricao')),
                ('energy_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='energia (kWh)')),
                ('unit_price_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='tarifa (R$/kWh)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor (R$)')),
                ('flagged_for_audit', models.BooleanField(default=False, verbose_name='marcada para auditoria')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.invoice')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='core.chargingsession')),
                ('reconciliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='core.tariffreconciliation')),
            ],
            options={
                'verbose_name': 'linha de fatura',
                'verbose_name_plural': 'linhas de fatura',
                'db_table': 'invoice_line',
            },
        ),
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(verbose_name='instante')),
                ('kind', models.TextField(choices=[('meter_value', 'Leitura de medidor'), ('heartbeat', 'Heartbeat'), ('status_change', 'Mudanca de estado')], verbose_name='tipo')),
                ('state', models.TextField(blank=True, choices=[('disconnected', 'Desconectado'), ('connected', 'Conectado'), ('charging', 'Carregando'), ('finished', 'Finalizado'), ('offline', 'Offline')], null=True, verbose_name='estado')),
                ('power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='potencia (kW)')),
                ('energy_kwh_total', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='medidor acumulado (kWh)')),
                ('measurement_source', models.TextField(choices=[('cloud', 'Nuvem do fabricante'), ('modbus_local', 'Modbus TCP local'), ('mid_meter', 'Medidor MID (RS-485)')], default='cloud', verbose_name='origem da medicao')),
                ('charge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.chargepoint')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.chargingsession')),
            ],
            options={
                'verbose_name': 'leitura de telemetria',
                'verbose_name_plural': 'leituras de telemetria',
                'db_table': 'telemetry_reading',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(verbose_name='identificacao')),
                ('block', models.TextField(blank=True, null=True, verbose_name='bloco')),
                ('ideal_fraction', models.DecimalField(blank=True, decimal_places=6, help_text='Cadastral. NAO participa do rateio (decisao 8): o rateio da taxa de disponibilidade e igual entre unidades aderentes.', max_digits=8, null=True, verbose_name='fracao ideal')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='core.condominium')),
            ],
            options={
                'verbose_name': 'unidade',
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='ProgramEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='inicio da adesao')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fim da adesao')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.unit')),
            ],
            options={
                'verbose_name': 'adesao ao programa',
                'verbose_name_plural': 'adesoes ao programa',
                'db_table': 'program_enrollment',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.unit'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Nula para visitante (decisao 3) e para gestor sem unidade.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='core.unit'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.TextField(unique=True, verbose_name='placa')),
                ('model', models.TextField(verbose_name='modelo')),
                ('battery_capacity_kwh', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='capacidade da bateria (kWh)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.appuser')),
            ],
            options={
                'verbose_name': 'veiculo',
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(choices=[('consumption', 'Consumo'), ('idle', 'Ociosidade'), ('power_degradation', 'Degradacao de potencia'), ('metering', 'Medicao'), ('health', 'Saude do ponto')], verbose_name='categoria')),
                ('explanation', models.TextField(help_text='Legivel por humano: "consumo 4x o padrao da credencial".', verbose_name='explicacao')),
                ('detector', models.TextField(default='rule', help_text='`rule` (fase 1, estatistica interpretavel) ou `isolation_forest` (fase 2).', verbose_name='detector')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='escore')),
                ('status', models.TextField(choices=[('open', 'Aberta'), ('accepted', 'Aceita'), ('contested', 'Contestada'), ('dismissed', 'Descartada')], default='open', verbose_name='situacao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='detectada em')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revisada em')),
                ('reviewed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_anomalies', to='core.appuser')),
                ('charge_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.chargepoint')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.chargingsession')),
            ],
            options={
                'verbose_name': 'anomalia',
                'verbose_name_plural': 'anomalias',
                'db_table': 'anomaly_flag',
                'constraints': [models.CheckConstraint(condition=models.Q(('session__isnull', False), ('charge_point__isnull', False), _connector='OR'), name='anomaly_targets_session_or_point'), models.CheckConstraint(condition=models.Q(('status__in', ['open', 'accepted', 'contested', 'dismissed'])), name='anomaly_status_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='credential',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['rfid', 'app'])), name='credential_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='credential',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'suspended', 'revoked'])), name='credential_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='tariffperiod',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='tariff_period_valid_range'),
        ),
        migrations.AddIndex(
            model_name='chargingsession',
            index=models.Index(fields=['charge_point', 'session_start'], name='charging_se_charge__6309ec_idx'),
        ),
        migrations.AddIndex(
            model_name='chargingsession',
            index=models.Index(fields=['credential', 'session_start'], name='charging_se_credent_8899e1_idx'),
        ),
        migrations.AddIndex(
            model_name='chargingsession',
            index=models.Index(fields=['session_start'], name='charging_se_session_27c5b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='chargingsession',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['in_progress', 'completed', 'interrupted', 'fault'])), name='session_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='chargingsession',
            constraint=models.CheckConstraint(condition=models.Q(('session_end__isnull', True), ('session_end__gte', models.F('session_start')), _connector='OR'), name='session_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='chargingsession',
            constraint=models.CheckConstraint(condition=models.Q(('energy_kwh__gte', 0)), name='session_energy_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='chargingsession',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'in_progress'), ('applied_tariff_kwh__isnull', False), _connector='OR'), name='session_closed_has_tariff_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='tariffreconciliation',
            constraint=models.UniqueConstraint(fields=('condominium', 'competence'), name='reconciliation_unique_per_competence'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['session', 'availability_fee', 'tariff_adjustment'])), name='invoice_line_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'session'), _negated=True), ('session__isnull', False), _connector='OR'), name='invoice_line_session_requires_fk'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'tariff_adjustment'), _negated=True), ('reconciliation__isnull', False), _connector='OR'), name='invoice_line_adjustment_requires_fk'),
        ),
        migrations.AddIndex(
            model_name='telemetryreading',
            index=models.Index(fields=['charge_point', 'ts'], name='telemetry_r_charge__fc411e_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryreading',
            index=models.Index(fields=['session', 'ts'], name='telemetry_r_session_c3f2b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='telemetryreading',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['meter_value', 'heartbeat', 'status_change'])), name='telemetry_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('condominium', 'label'), name='unit_label_unique_per_condo'),
        ),
        migrations.AddConstraint(
            model_name='programenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='enrollment_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('unit__isnull', False)), fields=('unit', 'competence'), name='invoice_unique_per_unit_competence'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'under_review', 'closed', 'paid', 'overdue'])), name='invoice_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('unit__isnull', False), ('visitor_user__isnull', True)), models.Q(('unit__isnull', True), ('visitor_user__isnull', False)), _connector='OR'), name='invoice_unit_xor_visitor'),
        ),
        migrations.AddConstraint(
            model_name='appuser',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['resident', 'manager', 'visitor'])), name='app_user_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='appuser',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'visitor'), _negated=True), ('unit__isnull', True), _connector='OR'), name='app_user_visitor_has_no_unit'),
        ),
    ]
