# Generated by Django 5.2.17 on 2026-08-22 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_no_overlap_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
        migrations.AlterModelOptions(
            name='chargingsession',
            options={'verbose_name': 'sessão de recarga', 'verbose_name_plural': 'sessões de recarga'},
        ),
        migrations.AlterModelOptions(
            name='condominium',
            options={'verbose_name': 'condomínio', 'verbose_name_plural': 'condomínios'},
        ),
        migrations.AlterModelOptions(
            name='programenrollment',
            options={'verbose_name': 'adesão ao programa', 'verbose_name_plural': 'adesões ao programa'},
        ),
        migrations.AlterModelOptions(
            name='tariffperiod',
            options={'verbose_name': 'vigência de tarifa', 'verbose_name_plural': 'vigências de tarifa'},
        ),
        migrations.AlterModelOptions(
            name='tariffreconciliation',
            options={'verbose_name': 'reconciliação de tarifa', 'verbose_name_plural': 'reconciliações de tarifa'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'veículo'},
        ),
        migrations.RemoveConstraint(
            model_name='programenrollment',
            name='enrollment_no_overlap_per_unit',
        ),
        migrations.RemoveConstraint(
            model_name='tariffperiod',
            name='tariff_period_no_overlap_per_condo',
        ),
        migrations.AlterField(
            model_name='anomalyflag',
            name='category',
            field=models.TextField(choices=[('consumption', 'Consumo'), ('idle', 'Ociosidade'), ('power_degradation', 'Degradação de potência'), ('metering', 'Medição'), ('health', 'Saúde do ponto')], verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='anomalyflag',
            name='explanation',
            field=models.TextField(help_text='Legivel por humano: "consumo 4x o padrao da credencial".', verbose_name='explicação'),
        ),
        migrations.AlterField(
            model_name='anomalyflag',
            name='status',
            field=models.TextField(choices=[('open', 'Aberta'), ('accepted', 'Aceita'), ('contested', 'Contestada'), ('dismissed', 'Descartada')], default='open', verbose_name='situação'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.TextField(choices=[('resident', 'Morador'), ('manager', 'Gestor/síndico'), ('visitor', 'Visitante')], default='resident', verbose_name='papel'),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='commissioned_at',
            field=models.DateField(verbose_name='em operação desde'),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='location',
            field=models.TextField(verbose_name='localização'),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='rated_power_kw',
            field=models.DecimalField(decimal_places=2, help_text='Denominador da razao kWh/hora usada na deteccao de anomalias.', max_digits=6, verbose_name='potência nominal (kW)'),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='serial_number',
            field=models.TextField(help_text='E o `charge_point_id` do contrato da Frente 2 (o `sn` do SEMS).', unique=True, verbose_name='número de série'),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='auth_method',
            field=models.TextField(choices=[('rfid', 'RFID'), ('app', 'App')], verbose_name='método'),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='max_power_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='potência máxima (kW)'),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='measurement_source',
            field=models.TextField(choices=[('cloud', 'Nuvem do fabricante'), ('modbus_local', 'Modbus TCP local'), ('mid_meter', 'Medidor MID (RS-485)')], default='cloud', verbose_name='origem da medição'),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='meter_start',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='medidor no início (kWh)'),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='session_start',
            field=models.DateTimeField(verbose_name='início'),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='status',
            field=models.TextField(choices=[('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('interrupted', 'Interrompida'), ('fault', 'Falha')], verbose_name='situação'),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='declared_power_kw',
            field=models.DecimalField(decimal_places=2, help_text='Teto da instalacao de recarga (Lei 18.403 / IT-41); limite do alerta de potencia da abordagem 1 de IA.', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='potência declarada (kW)'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='kind',
            field=models.TextField(choices=[('rfid', 'Cartão RFID'), ('app', 'Conta no app')], verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='status',
            field=models.TextField(choices=[('active', 'Ativa'), ('suspended', 'Suspensa'), ('revoked', 'Revogada')], default='active', verbose_name='situação'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='valid_from',
            field=models.DateField(verbose_name='válida desde'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='competence',
            field=models.CharField(max_length=7, verbose_name='competência'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.TextField(choices=[('draft', 'Rascunho'), ('under_review', 'Em auditoria'), ('closed', 'Fechada'), ('paid', 'Paga'), ('overdue', 'Em atraso')], default='draft', verbose_name='situação'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='description',
            field=models.TextField(verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='kind',
            field=models.TextField(choices=[('session', 'Sessão de recarga'), ('availability_fee', 'Taxa de disponibilidade'), ('tariff_adjustment', 'Ajuste de tarifa')], verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='programenrollment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='fim da adesão'),
        ),
        migrations.AlterField(
            model_name='programenrollment',
            name='start_date',
            field=models.DateField(verbose_name='início da adesão'),
        ),
        migrations.AlterField(
            model_name='tariffperiod',
            name='price_kwh',
            field=models.DecimalField(decimal_places=4, help_text='Provisoria de repasse (decisao 5). O efetivo entra depois, por linha de ajuste.', max_digits=8, verbose_name='tarifa provisória (R$/kWh)'),
        ),
        migrations.AlterField(
            model_name='tariffperiod',
            name='valid_to',
            field=models.DateField(blank=True, null=True, verbose_name='vigente até'),
        ),
        migrations.AlterField(
            model_name='tariffreconciliation',
            name='competence',
            field=models.CharField(max_length=7, verbose_name='competência apurada'),
        ),
        migrations.AlterField(
            model_name='tariffreconciliation',
            name='provisional_price_kwh',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name='tarifa provisória vigente (R$/kWh)'),
        ),
        migrations.AlterField(
            model_name='tariffreconciliation',
            name='settled_in_competence',
            field=models.CharField(help_text='Competencia cuja fatura carrega as linhas de ajuste.', max_length=7, verbose_name='liquidada na competência'),
        ),
        migrations.AlterField(
            model_name='telemetryreading',
            name='kind',
            field=models.TextField(choices=[('meter_value', 'Leitura de medidor'), ('heartbeat', 'Heartbeat'), ('status_change', 'Mudança de estado')], verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='telemetryreading',
            name='measurement_source',
            field=models.TextField(choices=[('cloud', 'Nuvem do fabricante'), ('modbus_local', 'Modbus TCP local'), ('mid_meter', 'Medidor MID (RS-485)')], default='cloud', verbose_name='origem da medição'),
        ),
        migrations.AlterField(
            model_name='telemetryreading',
            name='power_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='potência (kW)'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='ideal_fraction',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Cadastral. NAO participa do rateio (decisao 8): o rateio da taxa de disponibilidade e igual entre unidades aderentes.', max_digits=8, null=True, verbose_name='fração ideal'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='label',
            field=models.TextField(verbose_name='identificação'),
        ),
    ]
