# Generated by Django 5.2.17 on 2026-09-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rotulos_acentuados'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingsession',
            name='source',
            field=models.TextField(default='legacy', help_text='Nome do adaptador que trouxe a sessao (`sems_stub`, `semsplus_log`, `event_push`, `synthetic`...). Proveniencia: diante de uma contestacao, a primeira pergunta e de onde veio o numero.', verbose_name='fonte'),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='source_ref',
            field=models.TextField(blank=True, help_text='Id da sessao/transacao no sistema de origem. E a chave de idempotencia preferida: reentrega do mesmo evento acha a mesma sessao.', null=True, verbose_name='identificador na fonte'),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='meter_start',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Nulo = a fonte nao reporta medidor acumulado. E o caso do historico de sessoes do SEMS+ (evidencia [O] da Frente 2), que so entrega inicio, fim e energia. Exigir o campo obrigaria o adaptador a inventar um numero, e numero inventado em trilha de auditoria e pior que lacuna declarada.', max_digits=12, null=True, verbose_name='medidor no início (kWh)'),
        ),
        migrations.AddConstraint(
            model_name='chargingsession',
            constraint=models.UniqueConstraint(fields=('charge_point', 'session_start'), name='session_unique_per_point_start'),
        ),
        migrations.AddConstraint(
            model_name='chargingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('source_ref__isnull', False)), fields=('source', 'source_ref'), name='session_unique_per_source_ref'),
        ),
    ]
