# Generated by Django 5.2.17 on 2026-09-18 20:42

import core.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ingestao_robusta'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='programenrollment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(core.models.DateRange('start_date', 'end_date', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=True)), '&&'), ('unit', '=')], name='enrollment_no_overlap_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='tariffperiod',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(core.models.DateRange('valid_from', 'valid_to', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=True)), '&&'), ('condominium', '=')], name='tariff_period_no_overlap_per_condo'),
        ),
    ]
