# Generated by Django 5.2.17 on 2026-09-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_restaura_vigencias_sem_sobreposicao'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='anomalyflag',
            name='anomaly_status_valid',
        ),
        migrations.AddField(
            model_name='anomalyflag',
            name='resolution',
            field=models.TextField(blank=True, help_text='O que o gestor fez para encerrar um caso confirmado. Texto obrigatorio na resolucao: liberar cobranca retida sem dizer por que e o que a trilha de auditoria existe para impedir.', null=True, verbose_name='desfecho'),
        ),
        migrations.AddField(
            model_name='anomalyflag',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='resolvida em'),
        ),
        migrations.AlterField(
            model_name='anomalyflag',
            name='status',
            field=models.TextField(choices=[('open', 'Aberta'), ('accepted', 'Aceita'), ('contested', 'Contestada'), ('dismissed', 'Descartada'), ('resolved', 'Resolvida')], default='open', verbose_name='situação'),
        ),
        migrations.AddConstraint(
            model_name='anomalyflag',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'accepted', 'contested', 'dismissed', 'resolved'])), name='anomaly_status_valid'),
        ),
    ]
